# Generated by Django 4.0.3 on 2022-03-31 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bu yerda kategoriya nomini kiriting.', max_length=100)),
            ],
            options={
                'verbose_name': 'Kategoriya ',
                'verbose_name_plural': 'Kategoriyalar ',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Bu yerda mahsulot nomini kiriting.', max_length=400)),
                ('cost', models.IntegerField(help_text='Bu yerda mahsulot narxini kiriting.')),
                ('image', models.ImageField(upload_to='Products')),
                ('desc', models.TextField(help_text="Bu yerda mahsulot haqida qisqacha ma'lumot kiriting.")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
            options={
                'verbose_name': 'Mahsulot ',
                'verbose_name_plural': 'Mahsulotlar ',
            },
        ),
    ]
